        self.clicked00 = StringVar()
        self.clicked00.set(self.options[0])
        self.drop00 = OptionMenu(self.root, self.clicked00, *self.options, command=self.clicker00)
        self.drop00.grid(row=0,column=0)
        self.clicked01 = StringVar()
        self.clicked01.set(self.options[0])
        self.drop01 = OptionMenu(self.root, self.clicked01, *self.options, command=self.clicker01)
        self.drop01.grid(row=0,column=1)
        self.clicked02 = StringVar()
        self.clicked02.set(self.options[0])
        self.drop02 = OptionMenu(self.root, self.clicked02, *self.options, command=self.clicker02)
        self.drop02.grid(row=0,column=2)
        self.clicked10 = StringVar()
        self.clicked10.set(self.options[0])
        self.drop10 = OptionMenu(self.root, self.clicked10, *self.options, command=self.clicker10)
        self.drop10.grid(row=1,column=0)
        self.clicked11 = StringVar()
        self.clicked11.set(self.options[0])
        self.drop11 = OptionMenu(self.root, self.clicked11, *self.options, command=self.clicker11)
        self.drop11.grid(row=1,column=1)
        self.clicked12 = StringVar()
        self.clicked12.set(self.options[0])
        self.drop12 = OptionMenu(self.root, self.clicked12, *self.options, command=self.clicker12)
        self.drop12.grid(row=1,column=2)
        self.clicked20 = StringVar()
        self.clicked20.set(self.options[0])
        self.drop20 = OptionMenu(self.root, self.clicked20, *self.options, command=self.clicker20)
        self.drop20.grid(row=2,column=0)
        self.clicked21 = StringVar()
        self.clicked21.set(self.options[0])
        self.drop21 = OptionMenu(self.root, self.clicked21, *self.options, command=self.clicker21)
        self.drop21.grid(row=2,column=1)
        self.clicked22 = StringVar()
        self.clicked22.set(self.options[0])
        self.drop22 = OptionMenu(self.root, self.clicked22, *self.options, command=self.clicker22)
        self.drop22.grid(row=2,column=2)
