        self.clicked00 = StringVar()
        self.clicked00.set(self.options_list[0][0][0])
        self.drop00 = OptionMenu(self.root, self.clicked00, *self.options_list[0][0], command=self.clicker00)
        self.drop00.grid(row=0,column=0)
        self.clicked01 = StringVar()
        self.clicked01.set(self.options_list[0][1][0])
        self.drop01 = OptionMenu(self.root, self.clicked01, *self.options_list[0][1], command=self.clicker01)
        self.drop01.grid(row=0,column=1)
        self.clicked02 = StringVar()
        self.clicked02.set(self.options_list[0][2][0])
        self.drop02 = OptionMenu(self.root, self.clicked02, *self.options_list[0][2], command=self.clicker02)
        self.drop02.grid(row=0,column=2)
        self.clicked03 = StringVar()
        self.clicked03.set(self.options_list[0][3][0])
        self.drop03 = OptionMenu(self.root, self.clicked03, *self.options_list[0][3], command=self.clicker03)
        self.drop03.grid(row=0,column=3)
        self.clicked04 = StringVar()
        self.clicked04.set(self.options_list[0][4][0])
        self.drop04 = OptionMenu(self.root, self.clicked04, *self.options_list[0][4], command=self.clicker04)
        self.drop04.grid(row=0,column=4)
        self.clicked05 = StringVar()
        self.clicked05.set(self.options_list[0][5][0])
        self.drop05 = OptionMenu(self.root, self.clicked05, *self.options_list[0][5], command=self.clicker05)
        self.drop05.grid(row=0,column=5)
        self.clicked06 = StringVar()
        self.clicked06.set(self.options_list[0][6][0])
        self.drop06 = OptionMenu(self.root, self.clicked06, *self.options_list[0][6], command=self.clicker06)
        self.drop06.grid(row=0,column=6)
        self.clicked07 = StringVar()
        self.clicked07.set(self.options_list[0][7][0])
        self.drop07 = OptionMenu(self.root, self.clicked07, *self.options_list[0][7], command=self.clicker07)
        self.drop07.grid(row=0,column=7)
        self.clicked08 = StringVar()
        self.clicked08.set(self.options_list[0][8][0])
        self.drop08 = OptionMenu(self.root, self.clicked08, *self.options_list[0][8], command=self.clicker08)
        self.drop08.grid(row=0,column=8)
        self.clicked10 = StringVar()
        self.clicked10.set(self.options_list[1][0][0])
        self.drop10 = OptionMenu(self.root, self.clicked10, *self.options_list[1][0], command=self.clicker10)
        self.drop10.grid(row=1,column=0)
        self.clicked11 = StringVar()
        self.clicked11.set(self.options_list[1][1][0])
        self.drop11 = OptionMenu(self.root, self.clicked11, *self.options_list[1][1], command=self.clicker11)
        self.drop11.grid(row=1,column=1)
        self.clicked12 = StringVar()
        self.clicked12.set(self.options_list[1][2][0])
        self.drop12 = OptionMenu(self.root, self.clicked12, *self.options_list[1][2], command=self.clicker12)
        self.drop12.grid(row=1,column=2)
        self.clicked13 = StringVar()
        self.clicked13.set(self.options_list[1][3][0])
        self.drop13 = OptionMenu(self.root, self.clicked13, *self.options_list[1][3], command=self.clicker13)
        self.drop13.grid(row=1,column=3)
        self.clicked14 = StringVar()
        self.clicked14.set(self.options_list[1][4][0])
        self.drop14 = OptionMenu(self.root, self.clicked14, *self.options_list[1][4], command=self.clicker14)
        self.drop14.grid(row=1,column=4)
        self.clicked15 = StringVar()
        self.clicked15.set(self.options_list[1][5][0])
        self.drop15 = OptionMenu(self.root, self.clicked15, *self.options_list[1][5], command=self.clicker15)
        self.drop15.grid(row=1,column=5)
        self.clicked16 = StringVar()
        self.clicked16.set(self.options_list[1][6][0])
        self.drop16 = OptionMenu(self.root, self.clicked16, *self.options_list[1][6], command=self.clicker16)
        self.drop16.grid(row=1,column=6)
        self.clicked17 = StringVar()
        self.clicked17.set(self.options_list[1][7][0])
        self.drop17 = OptionMenu(self.root, self.clicked17, *self.options_list[1][7], command=self.clicker17)
        self.drop17.grid(row=1,column=7)
        self.clicked18 = StringVar()
        self.clicked18.set(self.options_list[1][8][0])
        self.drop18 = OptionMenu(self.root, self.clicked18, *self.options_list[1][8], command=self.clicker18)
        self.drop18.grid(row=1,column=8)
        self.clicked20 = StringVar()
        self.clicked20.set(self.options_list[2][0][0])
        self.drop20 = OptionMenu(self.root, self.clicked20, *self.options_list[2][0], command=self.clicker20)
        self.drop20.grid(row=2,column=0)
        self.clicked21 = StringVar()
        self.clicked21.set(self.options_list[2][1][0])
        self.drop21 = OptionMenu(self.root, self.clicked21, *self.options_list[2][1], command=self.clicker21)
        self.drop21.grid(row=2,column=1)
        self.clicked22 = StringVar()
        self.clicked22.set(self.options_list[2][2][0])
        self.drop22 = OptionMenu(self.root, self.clicked22, *self.options_list[2][2], command=self.clicker22)
        self.drop22.grid(row=2,column=2)
        self.clicked23 = StringVar()
        self.clicked23.set(self.options_list[2][3][0])
        self.drop23 = OptionMenu(self.root, self.clicked23, *self.options_list[2][3], command=self.clicker23)
        self.drop23.grid(row=2,column=3)
        self.clicked24 = StringVar()
        self.clicked24.set(self.options_list[2][4][0])
        self.drop24 = OptionMenu(self.root, self.clicked24, *self.options_list[2][4], command=self.clicker24)
        self.drop24.grid(row=2,column=4)
        self.clicked25 = StringVar()
        self.clicked25.set(self.options_list[2][5][0])
        self.drop25 = OptionMenu(self.root, self.clicked25, *self.options_list[2][5], command=self.clicker25)
        self.drop25.grid(row=2,column=5)
        self.clicked26 = StringVar()
        self.clicked26.set(self.options_list[2][6][0])
        self.drop26 = OptionMenu(self.root, self.clicked26, *self.options_list[2][6], command=self.clicker26)
        self.drop26.grid(row=2,column=6)
        self.clicked27 = StringVar()
        self.clicked27.set(self.options_list[2][7][0])
        self.drop27 = OptionMenu(self.root, self.clicked27, *self.options_list[2][7], command=self.clicker27)
        self.drop27.grid(row=2,column=7)
        self.clicked28 = StringVar()
        self.clicked28.set(self.options_list[2][8][0])
        self.drop28 = OptionMenu(self.root, self.clicked28, *self.options_list[2][8], command=self.clicker28)
        self.drop28.grid(row=2,column=8)
        self.clicked30 = StringVar()
        self.clicked30.set(self.options_list[3][0][0])
        self.drop30 = OptionMenu(self.root, self.clicked30, *self.options_list[3][0], command=self.clicker30)
        self.drop30.grid(row=3,column=0)
        self.clicked31 = StringVar()
        self.clicked31.set(self.options_list[3][1][0])
        self.drop31 = OptionMenu(self.root, self.clicked31, *self.options_list[3][1], command=self.clicker31)
        self.drop31.grid(row=3,column=1)
        self.clicked32 = StringVar()
        self.clicked32.set(self.options_list[3][2][0])
        self.drop32 = OptionMenu(self.root, self.clicked32, *self.options_list[3][2], command=self.clicker32)
        self.drop32.grid(row=3,column=2)
        self.clicked33 = StringVar()
        self.clicked33.set(self.options_list[3][3][0])
        self.drop33 = OptionMenu(self.root, self.clicked33, *self.options_list[3][3], command=self.clicker33)
        self.drop33.grid(row=3,column=3)
        self.clicked34 = StringVar()
        self.clicked34.set(self.options_list[3][4][0])
        self.drop34 = OptionMenu(self.root, self.clicked34, *self.options_list[3][4], command=self.clicker34)
        self.drop34.grid(row=3,column=4)
        self.clicked35 = StringVar()
        self.clicked35.set(self.options_list[3][5][0])
        self.drop35 = OptionMenu(self.root, self.clicked35, *self.options_list[3][5], command=self.clicker35)
        self.drop35.grid(row=3,column=5)
        self.clicked36 = StringVar()
        self.clicked36.set(self.options_list[3][6][0])
        self.drop36 = OptionMenu(self.root, self.clicked36, *self.options_list[3][6], command=self.clicker36)
        self.drop36.grid(row=3,column=6)
        self.clicked37 = StringVar()
        self.clicked37.set(self.options_list[3][7][0])
        self.drop37 = OptionMenu(self.root, self.clicked37, *self.options_list[3][7], command=self.clicker37)
        self.drop37.grid(row=3,column=7)
        self.clicked38 = StringVar()
        self.clicked38.set(self.options_list[3][8][0])
        self.drop38 = OptionMenu(self.root, self.clicked38, *self.options_list[3][8], command=self.clicker38)
        self.drop38.grid(row=3,column=8)
        self.clicked40 = StringVar()
        self.clicked40.set(self.options_list[4][0][0])
        self.drop40 = OptionMenu(self.root, self.clicked40, *self.options_list[4][0], command=self.clicker40)
        self.drop40.grid(row=4,column=0)
        self.clicked41 = StringVar()
        self.clicked41.set(self.options_list[4][1][0])
        self.drop41 = OptionMenu(self.root, self.clicked41, *self.options_list[4][1], command=self.clicker41)
        self.drop41.grid(row=4,column=1)
        self.clicked42 = StringVar()
        self.clicked42.set(self.options_list[4][2][0])
        self.drop42 = OptionMenu(self.root, self.clicked42, *self.options_list[4][2], command=self.clicker42)
        self.drop42.grid(row=4,column=2)
        self.clicked43 = StringVar()
        self.clicked43.set(self.options_list[4][3][0])
        self.drop43 = OptionMenu(self.root, self.clicked43, *self.options_list[4][3], command=self.clicker43)
        self.drop43.grid(row=4,column=3)
        self.clicked44 = StringVar()
        self.clicked44.set(self.options_list[4][4][0])
        self.drop44 = OptionMenu(self.root, self.clicked44, *self.options_list[4][4], command=self.clicker44)
        self.drop44.grid(row=4,column=4)
        self.clicked45 = StringVar()
        self.clicked45.set(self.options_list[4][5][0])
        self.drop45 = OptionMenu(self.root, self.clicked45, *self.options_list[4][5], command=self.clicker45)
        self.drop45.grid(row=4,column=5)
        self.clicked46 = StringVar()
        self.clicked46.set(self.options_list[4][6][0])
        self.drop46 = OptionMenu(self.root, self.clicked46, *self.options_list[4][6], command=self.clicker46)
        self.drop46.grid(row=4,column=6)
        self.clicked47 = StringVar()
        self.clicked47.set(self.options_list[4][7][0])
        self.drop47 = OptionMenu(self.root, self.clicked47, *self.options_list[4][7], command=self.clicker47)
        self.drop47.grid(row=4,column=7)
        self.clicked48 = StringVar()
        self.clicked48.set(self.options_list[4][8][0])
        self.drop48 = OptionMenu(self.root, self.clicked48, *self.options_list[4][8], command=self.clicker48)
        self.drop48.grid(row=4,column=8)
        self.clicked50 = StringVar()
        self.clicked50.set(self.options_list[5][0][0])
        self.drop50 = OptionMenu(self.root, self.clicked50, *self.options_list[5][0], command=self.clicker50)
        self.drop50.grid(row=5,column=0)
        self.clicked51 = StringVar()
        self.clicked51.set(self.options_list[5][1][0])
        self.drop51 = OptionMenu(self.root, self.clicked51, *self.options_list[5][1], command=self.clicker51)
        self.drop51.grid(row=5,column=1)
        self.clicked52 = StringVar()
        self.clicked52.set(self.options_list[5][2][0])
        self.drop52 = OptionMenu(self.root, self.clicked52, *self.options_list[5][2], command=self.clicker52)
        self.drop52.grid(row=5,column=2)
        self.clicked53 = StringVar()
        self.clicked53.set(self.options_list[5][3][0])
        self.drop53 = OptionMenu(self.root, self.clicked53, *self.options_list[5][3], command=self.clicker53)
        self.drop53.grid(row=5,column=3)
        self.clicked54 = StringVar()
        self.clicked54.set(self.options_list[5][4][0])
        self.drop54 = OptionMenu(self.root, self.clicked54, *self.options_list[5][4], command=self.clicker54)
        self.drop54.grid(row=5,column=4)
        self.clicked55 = StringVar()
        self.clicked55.set(self.options_list[5][5][0])
        self.drop55 = OptionMenu(self.root, self.clicked55, *self.options_list[5][5], command=self.clicker55)
        self.drop55.grid(row=5,column=5)
        self.clicked56 = StringVar()
        self.clicked56.set(self.options_list[5][6][0])
        self.drop56 = OptionMenu(self.root, self.clicked56, *self.options_list[5][6], command=self.clicker56)
        self.drop56.grid(row=5,column=6)
        self.clicked57 = StringVar()
        self.clicked57.set(self.options_list[5][7][0])
        self.drop57 = OptionMenu(self.root, self.clicked57, *self.options_list[5][7], command=self.clicker57)
        self.drop57.grid(row=5,column=7)
        self.clicked58 = StringVar()
        self.clicked58.set(self.options_list[5][8][0])
        self.drop58 = OptionMenu(self.root, self.clicked58, *self.options_list[5][8], command=self.clicker58)
        self.drop58.grid(row=5,column=8)
        self.clicked60 = StringVar()
        self.clicked60.set(self.options_list[6][0][0])
        self.drop60 = OptionMenu(self.root, self.clicked60, *self.options_list[6][0], command=self.clicker60)
        self.drop60.grid(row=6,column=0)
        self.clicked61 = StringVar()
        self.clicked61.set(self.options_list[6][1][0])
        self.drop61 = OptionMenu(self.root, self.clicked61, *self.options_list[6][1], command=self.clicker61)
        self.drop61.grid(row=6,column=1)
        self.clicked62 = StringVar()
        self.clicked62.set(self.options_list[6][2][0])
        self.drop62 = OptionMenu(self.root, self.clicked62, *self.options_list[6][2], command=self.clicker62)
        self.drop62.grid(row=6,column=2)
        self.clicked63 = StringVar()
        self.clicked63.set(self.options_list[6][3][0])
        self.drop63 = OptionMenu(self.root, self.clicked63, *self.options_list[6][3], command=self.clicker63)
        self.drop63.grid(row=6,column=3)
        self.clicked64 = StringVar()
        self.clicked64.set(self.options_list[6][4][0])
        self.drop64 = OptionMenu(self.root, self.clicked64, *self.options_list[6][4], command=self.clicker64)
        self.drop64.grid(row=6,column=4)
        self.clicked65 = StringVar()
        self.clicked65.set(self.options_list[6][5][0])
        self.drop65 = OptionMenu(self.root, self.clicked65, *self.options_list[6][5], command=self.clicker65)
        self.drop65.grid(row=6,column=5)
        self.clicked66 = StringVar()
        self.clicked66.set(self.options_list[6][6][0])
        self.drop66 = OptionMenu(self.root, self.clicked66, *self.options_list[6][6], command=self.clicker66)
        self.drop66.grid(row=6,column=6)
        self.clicked67 = StringVar()
        self.clicked67.set(self.options_list[6][7][0])
        self.drop67 = OptionMenu(self.root, self.clicked67, *self.options_list[6][7], command=self.clicker67)
        self.drop67.grid(row=6,column=7)
        self.clicked68 = StringVar()
        self.clicked68.set(self.options_list[6][8][0])
        self.drop68 = OptionMenu(self.root, self.clicked68, *self.options_list[6][8], command=self.clicker68)
        self.drop68.grid(row=6,column=8)
        self.clicked70 = StringVar()
        self.clicked70.set(self.options_list[7][0][0])
        self.drop70 = OptionMenu(self.root, self.clicked70, *self.options_list[7][0], command=self.clicker70)
        self.drop70.grid(row=7,column=0)
        self.clicked71 = StringVar()
        self.clicked71.set(self.options_list[7][1][0])
        self.drop71 = OptionMenu(self.root, self.clicked71, *self.options_list[7][1], command=self.clicker71)
        self.drop71.grid(row=7,column=1)
        self.clicked72 = StringVar()
        self.clicked72.set(self.options_list[7][2][0])
        self.drop72 = OptionMenu(self.root, self.clicked72, *self.options_list[7][2], command=self.clicker72)
        self.drop72.grid(row=7,column=2)
        self.clicked73 = StringVar()
        self.clicked73.set(self.options_list[7][3][0])
        self.drop73 = OptionMenu(self.root, self.clicked73, *self.options_list[7][3], command=self.clicker73)
        self.drop73.grid(row=7,column=3)
        self.clicked74 = StringVar()
        self.clicked74.set(self.options_list[7][4][0])
        self.drop74 = OptionMenu(self.root, self.clicked74, *self.options_list[7][4], command=self.clicker74)
        self.drop74.grid(row=7,column=4)
        self.clicked75 = StringVar()
        self.clicked75.set(self.options_list[7][5][0])
        self.drop75 = OptionMenu(self.root, self.clicked75, *self.options_list[7][5], command=self.clicker75)
        self.drop75.grid(row=7,column=5)
        self.clicked76 = StringVar()
        self.clicked76.set(self.options_list[7][6][0])
        self.drop76 = OptionMenu(self.root, self.clicked76, *self.options_list[7][6], command=self.clicker76)
        self.drop76.grid(row=7,column=6)
        self.clicked77 = StringVar()
        self.clicked77.set(self.options_list[7][7][0])
        self.drop77 = OptionMenu(self.root, self.clicked77, *self.options_list[7][7], command=self.clicker77)
        self.drop77.grid(row=7,column=7)
        self.clicked78 = StringVar()
        self.clicked78.set(self.options_list[7][8][0])
        self.drop78 = OptionMenu(self.root, self.clicked78, *self.options_list[7][8], command=self.clicker78)
        self.drop78.grid(row=7,column=8)
        self.clicked80 = StringVar()
        self.clicked80.set(self.options_list[8][0][0])
        self.drop80 = OptionMenu(self.root, self.clicked80, *self.options_list[8][0], command=self.clicker80)
        self.drop80.grid(row=8,column=0)
        self.clicked81 = StringVar()
        self.clicked81.set(self.options_list[8][1][0])
        self.drop81 = OptionMenu(self.root, self.clicked81, *self.options_list[8][1], command=self.clicker81)
        self.drop81.grid(row=8,column=1)
        self.clicked82 = StringVar()
        self.clicked82.set(self.options_list[8][2][0])
        self.drop82 = OptionMenu(self.root, self.clicked82, *self.options_list[8][2], command=self.clicker82)
        self.drop82.grid(row=8,column=2)
        self.clicked83 = StringVar()
        self.clicked83.set(self.options_list[8][3][0])
        self.drop83 = OptionMenu(self.root, self.clicked83, *self.options_list[8][3], command=self.clicker83)
        self.drop83.grid(row=8,column=3)
        self.clicked84 = StringVar()
        self.clicked84.set(self.options_list[8][4][0])
        self.drop84 = OptionMenu(self.root, self.clicked84, *self.options_list[8][4], command=self.clicker84)
        self.drop84.grid(row=8,column=4)
        self.clicked85 = StringVar()
        self.clicked85.set(self.options_list[8][5][0])
        self.drop85 = OptionMenu(self.root, self.clicked85, *self.options_list[8][5], command=self.clicker85)
        self.drop85.grid(row=8,column=5)
        self.clicked86 = StringVar()
        self.clicked86.set(self.options_list[8][6][0])
        self.drop86 = OptionMenu(self.root, self.clicked86, *self.options_list[8][6], command=self.clicker86)
        self.drop86.grid(row=8,column=6)
        self.clicked87 = StringVar()
        self.clicked87.set(self.options_list[8][7][0])
        self.drop87 = OptionMenu(self.root, self.clicked87, *self.options_list[8][7], command=self.clicker87)
        self.drop87.grid(row=8,column=7)
        self.clicked88 = StringVar()
        self.clicked88.set(self.options_list[8][8][0])
        self.drop88 = OptionMenu(self.root, self.clicked88, *self.options_list[8][8], command=self.clicker88)
        self.drop88.grid(row=8,column=8)
